bbh

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,11 +1,24 @@
-#!/usr/bin/env bash
-# Transfers a file from a client to a server
-if [ "$#" -lt 3 ]
-then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -eq 3 ]
-then
-    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
-else
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
+#!/bin/bash
+
+# Check if the number of arguments is less than 4, display usage message
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
+
+# Assign arguments to variables
+file_path=$1
+server_ip=$2
+username=$3
+ssh_key=$4
+
+# Use scp to transfer the file to the server's home directory
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~
+
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transfer successful!"
+else
+    echo "File transfer failed!"
+fi
+
